/* Agent 0815 — Die fünf Fälle (Daten) */
let CASES = null;
const buildCases = () => {
  const O = Art.obj;
  const D = (who, text, opt = {}) => ({ type: 'dialog', who, text, ...opt });

  // Verdächtigen-Karte (Kopf + Gegenstand)
  const suspect = (who, item, label) => ({ who, item, label });
  const NINO = { who: 'nino', x: 300, y: 292, h: 170 }, NINO_L = { who: 'nino', x: 85, y: 292, h: 155 };
  // SVG-Fallbacks für neue Objekte (bis das Gemini-Bild da ist)
  const SV = {
    silberglocke: Scene0815.svgs.silberglocke,
    lieferwagen: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-30" y="-14" width="44" height="24" rx="3" fill="#F4F4F4" stroke="#888"/><path d="M14 -8 L26 -8 L30 2 L30 10 L14 10 Z" fill="#E8E8E8" stroke="#888"/><rect x="17" y="-5" width="9" height="7" fill="#9ED3EC"/><circle cx="-16" cy="12" r="5" fill="#333"/><circle cx="20" cy="12" r="5" fill="#333"/></g>`,
    auto: (x, y, s, col = '#B5533C') => `<g transform="translate(${x} ${y}) scale(${s})"><path d="M-28 6 L-22 -6 L-6 -12 L12 -12 L22 -4 L30 6 Z" fill="${col}" stroke="#7a3a2a"/><rect x="-4" y="-9" width="12" height="7" fill="#9ED3EC"/><circle cx="-16" cy="8" r="5" fill="#333"/><circle cx="18" cy="8" r="5" fill="#333"/><path d="M-10 -4 Q-6 -8 -2 -4" stroke="#7a3a2a" fill="none"/></g>`,
    muenzen: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><circle cx="-6" cy="4" r="9" fill="#F2B233" stroke="#B87326"/><circle cx="6" cy="-2" r="9" fill="#F7D046" stroke="#B87326"/><circle cx="2" cy="8" r="9" fill="#F2B233" stroke="#B87326"/></g>`,
    tablett: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-16" y="-4" width="32" height="8" rx="2" fill="#C29A6A" stroke="#8B6B44"/><ellipse cx="-8" cy="-6" rx="5" ry="3" fill="#E09A3E"/><ellipse cx="2" cy="-6" rx="5" ry="3" fill="#E09A3E"/><ellipse cx="11" cy="-6" rx="4" ry="3" fill="#E09A3E"/></g>`,
    schachtel: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-14" y="-8" width="28" height="18" fill="#C8A165" stroke="#8B6B44"/><path d="M-14 -8 L0 -14 L14 -8" fill="#D9B77A" stroke="#8B6B44"/><path d="M-6 -2 H6" stroke="#8B6B44" stroke-width="1.5"/></g>`,
    wind: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})" fill="none" stroke="#4FC3E8" stroke-width="3" stroke-linecap="round"><path d="M-16 -6 H8 a4 4 0 1 0 -4 -4"/><path d="M-16 4 H14 a4 4 0 1 1 -4 4"/></g>`,
    boese: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><circle r="18" fill="#F25C7A"/><path d="M-10 -6 L-3 -2 M10 -6 L3 -2" stroke="#222" stroke-width="2.5"/><path d="M-8 8 Q0 2 8 8" stroke="#222" stroke-width="2.5" fill="none"/></g>`,
    angst: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><circle r="18" fill="#9ED3EC"/><circle cx="-6" cy="-3" r="3" fill="#222"/><circle cx="6" cy="-3" r="3" fill="#222"/><ellipse cx="0" cy="8" rx="4" ry="5" fill="#222"/><path d="M-11 -10 Q-6 -13 -2 -9 M11 -10 Q6 -13 2 -9" stroke="#222" stroke-width="2" fill="none"/></g>`,
    wuetend: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><circle r="18" fill="#F25C7A"/><path d="M-10 -7 L-3 -3 M10 -7 L3 -3" stroke="#222" stroke-width="2.5"/><path d="M-8 9 Q0 3 8 9" stroke="#222" stroke-width="2.5" fill="none"/><path d="M14 -20 L10 -12 L15 -12 L11 -4" stroke="#F7D046" stroke-width="2.5" fill="none"/></g>`,
    unsichtbar: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})" opacity=".35"><circle r="18" fill="#9AA0A8"/><circle cx="-6" cy="-3" r="2.5" fill="#222"/><circle cx="6" cy="-3" r="2.5" fill="#222"/><path d="M-6 8 Q0 6 6 8" stroke="#222" stroke-width="2" fill="none"/></g>`,
    kuh: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><ellipse rx="26" ry="14" fill="#8B5A2B"/><rect x="-22" y="8" width="6" height="14" fill="#6B3F1A"/><rect x="14" y="8" width="6" height="14" fill="#6B3F1A"/><circle cx="26" cy="-8" r="9" fill="#8B5A2B"/><rect x="22" y="-4" width="10" height="7" rx="3" fill="#E8C4A0"/><circle cx="28" cy="-11" r="1.5" fill="#222"/><path d="M20 -16 L16 -22 M32 -16 L36 -22" stroke="#6B3F1A" stroke-width="2"/></g>`,
    erde: W => `<rect width="${W}" height="${W}" fill="#6B4A2B"/>${Array.from({ length: 40 }, (_, i) => `<circle cx="${(i * 53) % W}" cy="${(i * 37 + 11) % W}" r="${3 + i % 4}" fill="#5A3A22" opacity=".8"/>`).join('')}${Array.from({ length: 12 }, (_, i) => `<circle cx="${(i * 91 + 20) % W}" cy="${(i * 67 + 30) % W}" r="2" fill="#8B6B44"/>`).join('')}`,
    kiste: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-40" y="-16" width="80" height="40" rx="4" fill="#8B5A2B" stroke="#5A3A22" stroke-width="2"/><rect x="-42" y="-24" width="84" height="14" rx="4" fill="#A0522D" stroke="#5A3A22" stroke-width="2"/><rect x="-6" y="-14" width="12" height="10" fill="#C9A227"/><circle cx="-18" cy="-6" r="6" fill="#F2B233" stroke="#B87326"/><circle cx="-18" cy="-6" r="2.5" fill="#F25C7A"/><circle cx="16" cy="-4" r="9" fill="#E6E9EE" stroke="#8C93A0" stroke-width="2"/><path d="M16 -9 V-4 H20" stroke="#555" stroke-width="1.5" fill="none"/><path d="M-4 4 L4 -2 L8 6" stroke="#F2B233" stroke-width="3" fill="none"/></g>`,
    leder: W => `<rect width="${W}" height="${W}" rx="14" fill="#7A4A22"/>${Array.from({ length: 6 }, (_, i) => `<path d="M${20 + i * 40} 20 V${W - 20}" stroke="#5A3A22" stroke-width="1.5" stroke-dasharray="4 5"/>`).join('')}<rect x="18" y="18" width="${W - 36}" height="${W - 36}" rx="10" fill="none" stroke="#5A3A22" stroke-width="2" stroke-dasharray="4 5"/><rect x="${W / 2 - 16}" y="${W / 2 - 10}" width="32" height="20" rx="3" fill="#C9A227" stroke="#8A6A10"/>`,
    messingstreifen: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-70" y="-12" width="140" height="24" rx="3" fill="#C9A227" stroke="#8A6A10" stroke-width="2"/><circle cx="-48" cy="0" r="5" fill="#F3E9C8"/><circle cx="0" cy="0" r="5" fill="#F3E9C8"/><circle cx="44" cy="0" r="5" fill="#F3E9C8"/><rect x="-28" y="-3" width="16" height="6" fill="#F3E9C8"/><rect x="14" y="-3" width="16" height="6" fill="#F3E9C8"/><circle cx="62" cy="0" r="6" fill="#F3E9C8"/></g>`,
    bauplan: () => `<rect x="40" y="60" width="220" height="170" /><path d="M40 140 H150 M150 60 V140 M200 140 V230 M150 140 H260"/><path d="M60 60 V50 M120 60 V50 M40 200 H30" /><rect x="180" y="80" width="40" height="30"/><circle cx="90" cy="180" r="14"/><path d="M60 100 H120 M60 110 H120 M60 120 H120" stroke-width=".8"/>`,
    zettelpapier: W => `<rect x="4" y="4" width="${W - 8}" height="${W - 8}" rx="6" fill="#FFFFFF" stroke="#D9D9D9" stroke-width="3"/><circle cx="${W / 2}" cy="14" r="5" fill="#B5533C"/>`,
    uvlicht: () => `<g><circle r="40" fill="#8A2BE2" opacity=".35"/><circle r="40" fill="none" stroke="#C77DFF" stroke-width="3"/></g>`,
    uvbild: kind => {
      const bg = `<rect width="260" height="260" fill="#1a1230"/>`;
      const pen = 'stroke="#C77DFF" stroke-width="3" fill="none" stroke-linecap="round"';
      const lines = `<g ${pen} opacity=".7">${[60, 78, 96].map(y => `<path d="M40 ${y + 130} H${120 + (y % 30)}"/>`).join('')}</g>`;
      if (kind === 'bruecke') return bg + `<g ${pen}><path d="M30 120 Q130 60 230 120"/><path d="M30 130 H230"/><path d="M60 130 V112 M100 130 V96 M140 130 V90 M180 130 V96 M215 130 V112"/><path d="M20 130 L30 150 M240 130 L230 150" stroke-dasharray="4 4"/></g>` + lines;
      if (kind === 'brunnen') return bg + `<g ${pen}><rect x="70" y="90" width="120" height="50" rx="6"/><rect x="120" y="40" width="20" height="50"/><path d="M190 120 q10 20 6 40" /><circle cx="200" cy="170" r="4" fill="#C77DFF"/><circle cx="198" cy="184" r="3" fill="#C77DFF"/></g>` + lines;
      return bg + `<g ${pen}><rect x="50" y="100" width="160" height="20" rx="4"/><path d="M70 120 V160 M190 120 L200 160"/><path d="M180 120 L170 145" stroke-dasharray="3 3"/><path d="M60 90 Q130 70 200 90"/></g>` + lines;
    },
    bruecke_klein: () => `<g transform="translate(0 -2)"><path d="M-16 4 Q0 -8 16 4" stroke="#8B5A2B" stroke-width="3" fill="none"/><path d="M-16 6 H16" stroke="#8B5A2B" stroke-width="3"/></g>`,
    brunnen_klein: () => `<g><rect x="-12" y="-2" width="24" height="10" rx="2" fill="#9AA0A8"/><rect x="-3" y="-12" width="6" height="10" fill="#9AA0A8"/><circle cx="14" cy="10" r="2" fill="#4FC3E8"/></g>`,
    bank_klein: () => `<g><rect x="-14" y="-4" width="28" height="6" rx="2" fill="#8B5A2B"/><path d="M-10 2 V10 M10 2 L13 10" stroke="#8B5A2B" stroke-width="3"/></g>`,
    bank_grau: W => `<rect width="${W}" height="${W}" fill="#D9E4D0"/><rect x="30" y="${W * 0.45}" width="200" height="26" rx="6" fill="#8C8C86" stroke="#5A5A55" stroke-width="2"/><rect x="30" y="${W * 0.3}" width="200" height="22" rx="6" fill="#8C8C86" stroke="#5A5A55" stroke-width="2"/><path d="M50 ${W * 0.55} V${W * 0.8} M210 ${W * 0.55} V${W * 0.8}" stroke="#5A5A55" stroke-width="8"/><rect x="0" y="${W * 0.8}" width="${W}" height="${W * 0.2}" fill="#7DA85A"/>`,
    bank_blau: W => `<rect width="${W}" height="${W}" fill="#D9E4D0"/><rect x="30" y="${W * 0.45}" width="200" height="26" rx="6" fill="#2F5DA8" stroke="#1d3d70" stroke-width="2"/><rect x="30" y="${W * 0.3}" width="200" height="22" rx="6" fill="#2F5DA8" stroke="#1d3d70" stroke-width="2"/><path d="M50 ${W * 0.55} V${W * 0.8} M210 ${W * 0.55} V${W * 0.8}" stroke="#1d3d70" stroke-width="8"/><rect x="0" y="${W * 0.8}" width="${W}" height="${W * 0.2}" fill="#7DA85A"/>`,
    pinsel: () => `<g><rect x="-4" y="-26" width="8" height="30" rx="2" fill="#C29A6A" stroke="#8B6B44"/><path d="M-6 4 H6 L5 18 H-5 Z" fill="#2F5DA8"/></g>`,
    notizbuch: (x, y, s) => `<g transform="translate(${x} ${y}) scale(${s})"><rect x="-10" y="-13" width="20" height="26" rx="2" fill="#2F5DA8" stroke="#1d3d70"/><path d="M-6 -6 H6 M-6 0 H6 M-6 6 H3" stroke="#fff" stroke-width="1.5"/></g>`,
  };

  return [
    // ===================== FALL 1 — Das verschwundene Glöckchen (Buch 01, V6) =====================
    {
      id: 0, title: 'Das verschwundene Glöckchen', place: 'Brunnen', scene: 'marktplatz', tool: 'lupe_sprung',
      steps: [
        D('erz', 'Es gibt Tage, an denen in Bärlingen rein gar nichts passiert. Die Enten schwimmen im Brunnen. Und Herr Bühler redet mit seinen Gipfeli.', { scene: { name: 'marktplatz', opts: { bell: true } }, pause: 1400 }),
        D('erz', 'Und dann gibt es Tage wie diesen.', { scene: { name: 'gartenhaus', opts: { actors: [NINO] } } }),
        D('nino', 'Ohne Sonnenbrille bin ich nur Nino. Mit Sonnenbrille bin ich Agent 0815. Vom S G D. Dem Schweizerischen Geheim-Dienst.', { anim: 'brille' }),
        D('mila', 'Ich bin jetzt auch ein Agent!', { scene: { name: 'gartenhaus', opts: { actors: [NINO, { who: 'mila', x: 105, y: 292, h: 140, enter: 'left' }] } }, sfx: 'pop' }),
        D('nino', 'Raus. Geheim heisst geheim.'),
        D('mila', 'MAMA! NINO SPIELT WIEDER GEHEIMDIENST!', { cue: { type: 'shake', who: 'mila', at: 'start' } }),
        D('buehler', 'Weisch was, Nino! Meine Katze hat die ganze Nacht gefaucht. Wegen einem Lieferwagen, der gestunken hat. Und das Glöckchen vom Brunnen ist übrigens auch weg.', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'buehler', x: 310, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'Das Bärglöckchen? Die kleine silberne Glocke vom Brunnen? Agent 0815 übernimmt.', { cue: { type: 'brille', from: { x: 90, y: 150 }, to: { x: 250, y: 232 }, landing: 'klack', arc: 90 } }),
        D('buehler', 'Hey! Die sind für Kunden!'),
        D('brunner', 'Wahrscheinlich der Wind.', { scene: { name: 'marktplatz', opts: { bell: false, actors: [{ who: 'brunner', x: 325, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'Kann Wind vier Schrauben lösen?'),
        D('brunner', 'Ein STARKER Wind.'),
        D('mila', 'ES WAR NICHT DER WIND!', { scene: { name: 'marktplatz', opts: { bell: false, actors: [{ who: 'brunner', x: 325, y: 292, h: 175 }, NINO_L, { who: 'mila', x: 190, y: 292, h: 120, enter: 'pop' }] } }, sfx: 'pop' }),
        {
          type: 'find', scene: 'marktplatz', sceneOpts: { bell: false }, lupe: true,
          intro: { who: 'nino', text: 'Die Zwinkerlupe von Opa Ernst. Sie hat einen Sprung im Glas. Fahr mit der Lupe über den Brunnen. Findest du drei Spuren?' },
          hotspots: [
            { x: 205, y: 131, r: 16, label: 'Vier leere Schraubenlöcher', say: 'Vier Löcher. Hier war die Glocke mit vier Schrauben festgeschraubt.', svg: `<g fill="#3a3a3a">${[-9, -3, 3, 9].map(dx => `<circle cx="${205 + dx}" cy="131" r="1.6"/>`).join('')}</g>` },
            { x: 207, y: 162, r: 18, label: 'Kratzer', say: 'Ein Kratzer. Und noch einer. Jemand hat die Schrauben mit Werkzeug gelöst.', svg: `<g stroke="#3a2a1a" stroke-width="1.6" stroke-linecap="round" opacity=".85"><path d="M199 156 L215 166"/><path d="M200 168 L214 158"/><path d="M203 162 L213 163"/></g>` },
            { x: 335, y: 268, r: 22, label: 'Reifenspur', say: 'Eine Reifenspur. Breit. Hier stand ein Lieferwagen.', svg: `<g stroke="#4a3a2a" stroke-width="5" fill="none" opacity=".5" stroke-dasharray="5 4"><path d="M300 258 Q335 262 372 256"/><path d="M302 276 Q337 280 374 274"/></g>` },
          ],
          done: { who: 'nino', text: 'Drei Spuren. Kein Wind. Werkzeug und ein Lieferwagen.' },
        },
        D('erz', 'Nino beugt sich näher. Noch ein Stück. Er hält den Atem an, und —', { scene: { name: 'marktplatz', opts: { bell: false, actors: [NINO_L] } }, cue: { type: 'brille', at: 'end', from: { x: 80, y: 170 }, to: { x: 205, y: 222 }, landing: 'splash', quack: true, arc: 110 }, sfx: 'bonk' }),
        D('leyla', 'Schon wieder eine Einzeloperation?', { scene: { name: 'marktplatz', opts: { bell: false, actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165, enter: 'right' }] } } }),
        D('nino', 'Jemand hat die Glocke abgeschraubt. Und die Katze von Herrn Bühler hat einen Lieferwagen gerochen.'),
        D('leyla', 'Die zuverlässigste Zeugin in ganz Bärlingen.'),
        D('gerber', 'Weisser Lieferwagen. Genfer Nummern. Halb elf. Ein Herr Schlatter. Händler. Gauner.', { scene: { name: 'marktplatz', opts: { bell: false, actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        {
          type: 'choose', layout: 'icons',
          question: { who: 'nino', text: 'Frau Gerber hat ihn gesehen. Welches Fahrzeug war es? Tipp darauf.' },
          options: [
            { label: 'Postauto', img: 'postauto', svg: O.postauto(0, 0, 0.7), sfx: 'horn', correct: false, say: 'Das Postauto fährt jeden Tag durch Bärlingen. Das war nicht der Lieferwagen.' },
            { label: 'Lieferwagen', img: 'lieferwagen', svg: SV.lieferwagen(0, 0, 1), correct: true, say: 'Der weisse Lieferwagen. Mit Genfer Nummern. Der hat gestunken.' },
            { label: 'Rostiges Auto', img: 'auto_rost', svg: SV.auto(0, 0, 1, '#B5533C'), sfx: 'car', correct: false, say: 'Das ist Herrn Mettlers Auto. Das fährt nicht einmal.' },
          ],
          hint: { who: 'leyla', text: 'Frau Gerber hat gesagt: weiss. Und gross.' },
        },
        D('gerber', 'Das Bärglöckchen ist echtes Silber. Uralt. Stell die richtigen Fragen. Das hat dein Grossvater auch immer gemacht.', { scene: { name: 'marktplatz', opts: { bell: false, actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('schlatter', 'Ich war wegen einer Kuckucksuhr in Bärlingen. Danach habe ich im Restaurant gegessen. Den ganzen Abend. Fragen Sie die Wirtin.', { scene: { name: 'schlatter', opts: { actors: [{ who: 'schlatter', x: 300, y: 292, h: 175 }, NINO_L, { who: 'leyla', x: 165, y: 292, h: 140 }] } } }),
        D('nino', 'Eine Kuckucksuhr. Ein Restaurant. Das klingt alles ganz normal. Agent 0815 steckt fest.', { scene: { name: 'gartenhaus', opts: { fx: 'dusk', actors: [NINO] } } }),
        D('opa', 'Wenn du nicht weiterweisst: Wer hatte NICHTS davon?', { sfx: 'whoosh' }),
        {
          type: 'choose',
          question: { who: 'nino', text: 'Wer hatte nichts davon? Wer wollte die Glocke gar nicht verkaufen? Tipp darauf.' },
          options: [
            { ...suspect('schlatter', SV.muenzen(0, 0, 1), 'Herr Schlatter'), img: 'muenzen', correct: false, say: 'Herr Schlatter wollte die Glocke verkaufen. Der hatte etwas davon.' },
            { ...suspect('kummer', O.schraubenzieher(0, 0, 1.4), 'Herr Kummer'), img: 'schraubenzieher', correct: true, say: 'Herr Kummer! Der Hausmeister. Er wollte nur, dass die Glocke bleibt, wo sie hingehört.' },
            { ...suspect('brunner', SV.notizbuch(0, 0, 1), 'Onkel Brunner'), img: 'notizbuch', correct: false, say: 'Onkel Brunner sagt: der Wind. Er hat gar nichts gemacht.' },
          ],
          hint: { who: 'leyla', text: 'Wer hat eine Werkstatt voller Werkzeug? Und wer sagt nie etwas?' },
        },
        {
          type: 'taps', scene: { name: 'schulflur', opts: {} }, sequential: true,
          intro: { who: 'nino', text: 'Im Schulhaus riecht es nach Putzmittel. Vor der Werkstatt bleibe ich stehen. Klopf an die Tür. Dreimal.' },
          hint: 'Klopf an die Tür. Dort, wo es leuchtet.',
          targets: [{ x: 200, y: 145, r: 24, sfx: 'knock1' }, { x: 200, y: 180, r: 24, sfx: 'knock1' }, { x: 200, y: 215, r: 24, sfx: 'knock1' }],
          done: { who: 'kummer', text: 'Hat lang genug gedauert.' },
        },
        D('nino', 'Herr Kummer. Sie haben das Bärglöckchen. Aber nicht gestohlen. Gerettet.', { scene: { name: 'werkstatt', opts: { actors: [{ who: 'kummer', x: 310, y: 292, h: 180 }, NINO_L], extra: Art.sprite('silberglocke', 150, 185, 44, SV.silberglocke(150, 185, 1.1)) } } }),
        D('kummer', 'Dieser Schlatter ist ein Gauner. Das wusste dein Grossvater. Und dein Onkel hätte gesagt …'),
        D('nino', '… es war der Wind.'),
        D('kummer', 'Dein Grossvater hat auf die Dinge aufgepasst, die andere nicht sehen. Sieht aus, als macht das jetzt jemand anders.'),
        {
          type: 'taps', scene: { name: 'marktplatz', opts: { bell: true, actors: [{ who: 'kummer', x: 330, y: 292, h: 175 }] } },
          intro: { who: 'kummer', text: 'Die Glocke kommt zurück. Mit sechs Schrauben statt vier. Dreh jede Schraube fest.' },
          hint: 'Tipp auf eine Schraube, die noch leuchtet.',
          targets: [[-26, 0], [0, 0], [26, 0], [-26, 14], [0, 16], [26, 14]].map(([dx, dy]) => ({ x: 205 + dx, y: 136 + dy, r: 13, sfx: 'screw', spin: true, svg: `<g class="spin"><circle r="6" fill="#B9BFC9" stroke="#6B7078" stroke-width="1.2"/><path d="M-3.5 0 H3.5 M0 -3.5 V3.5" stroke="#4a4a4a" stroke-width="1.4"/></g>` })),
          done: { who: 'nino', text: 'Fest. Das Bärglöckchen glänzt wieder. Und Frau Imhof hatte gar keine Kuckucksuhr. Herr Schlatter hat gelogen.' },
        },
        D('gerber', 'Dein Grossvater hätte das genauso gemacht. Eine Spur schneller vielleicht. Aber er hatte mehr Übung.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('mila', 'ICH hab den Fall gelöst. Es war der Hausmeister. Das war doch total klar.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [{ who: 'mila', x: 200, y: 292, h: 140, enter: 'pop' }, NINO_L, { who: 'leyla', x: 320, y: 292, h: 160 }] } }, sfx: 'pop' }),
        D('leyla', 'Total klar.'),
        { type: 'reward', note: 'Genügend', zettel: { text: 'Gut gemacht, Nino. Das nächste Werkzeug findest du unter dem Boden vom Gartenhaus.', icon: 'eckengucker' } },
      ],
    },

    // ===================== FALL 2 — Der falsche Bäcker (Buch 02, V6) =====================
    {
      id: 1, title: 'Der falsche Bäcker', place: 'Bäckerei', scene: 'markt', tool: 'eckengucker',
      steps: [
        D('erz', 'Jeden dritten Samstag ist Markt in Bärlingen. Von draussen dringt Marktlärm ins Gartenhaus. Rufen, Karren, das Klappern von Blechständern.', { scene: { name: 'gartenhaus', opts: { actors: [NINO] } } }),
        {
          type: 'find', scene: { name: 'gartenhaus', opts: {} }, lupe: false,
          intro: { who: 'nino', text: 'Heute knarrt eine Diele anders. Nicht lauter. Hohler. Tipp auf die Dielen. Welche klingt hohl?' },
          hint: 'Tipp auf die Bretter am Boden. Eines klingt anders.',
          hotspots: [{ x: 232, y: 262, r: 32, label: 'Hohle Diele', say: 'Hohl! Und da, ins Holz geritzt: E. N. Die Diele lässt sich lösen.', svg: `<path d="M196 252 L268 246" stroke="#2a1a0a" stroke-width="3" opacity=".6"/>` }],
          misses: [{ x: 120, y: 268, r: 40, sfx: 'knock1', say: 'Die klingt normal.' }, { x: 330, y: 270, r: 40, sfx: 'knock1', say: 'Die auch. Weiter suchen.' }],
          done: { who: 'nino', text: 'Ein Messingrohr mit zwei Spiegeln. Der Eckengucker. Damit sehe ich um die Ecke, ohne mich umzudrehen.' },
        },
        D('mila', 'ICH WAR SCHON DIE GANZE ZEIT HIER. Das Ding ist COOL.', { scene: { name: 'gartenhaus', opts: { actors: [NINO, { who: 'mila', x: 105, y: 292, h: 140, enter: 'pop' }] } }, sfx: 'pop' }),
        D('nino', 'Raus. Geheim heisst geheim.'),
        D('mila', 'MAMA! NINO HAT ETWAS UNTER DEM BODEN GEFUNDEN!', { cue: { type: 'shake', who: 'mila', at: 'start' } }),
        D('erz', 'Auf dem Marktplatz riecht es nach Brot. Die Kirchturmuhr schlägt neun. Also ist es drei nach neun. Die Uhr geht immer nach. Das weiss jedes Kind. Sogar die Enten.', { scene: { name: 'markt', opts: { ducks: true } }, sfx: 'bell' }),
        D('buehler', 'Weisch was, Nino. Ich hab heimlich eine Kostprobe von diesem Wanderbäcker genommen. Schmeckt nach Plastik. Und Halbpreis! Für den Preis kriegst du sonst eine ganze Käserei.', { scene: { name: 'markt', opts: { actors: [{ who: 'buehler', x: 90, y: 292, h: 175 }, { who: 'nino', x: 310, y: 292, h: 150 }] } } }),
        D('leyla', 'Nino. Mamas Kasse fehlt. Weg. Seit einer Stunde.', { scene: { name: 'markt', opts: { actors: [{ who: 'nino', x: 310, y: 292, h: 150 }, { who: 'leyla', x: 90, y: 292, h: 165, enter: 'left' }] } } }),
        D('brunner', 'Wahrscheinlich der Wind.', { scene: { name: 'markt', opts: { actors: [{ who: 'brunner', x: 325, y: 292, h: 175 }, NINO_L, { who: 'leyla', x: 190, y: 292, h: 140 }] } } }),
        D('nino', 'Kann Wind eine Kasse stehlen?'),
        D('brunner', 'Ein sehr STARKER Wind.'),
        D('gerber', 'Ein Fremder am Markt. Und am selben Morgen fehlt eine Kasse. Für die meisten: eindeutig.', { scene: { name: 'markt', opts: { actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('nino', 'Für die meisten. Zwischen den Ständen ist eine schmale Gasse. Zu eng für Erwachsene. Einzeloperation.'),
        D('leyla', 'Ich stehe seit zehn Minuten hier.', { scene: { name: 'markt', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165, enter: 'right' }] } } }),
        {
          type: 'periscope', scene: { name: 'markt', opts: {} }, hidden: { name: 'markt_hinter' }, r: 60,
          intro: { who: 'nino', text: 'Schieb den Eckengucker bis zur Ecke. Im Spiegel siehst du hinter den Stand. Was versteckt der junge Mann? Tipp darauf.' },
          hotspots: [
            { x: 140, y: 170, r: 36, label: 'Kartonschachtel', say: 'Eine Kartonschachtel. Fabrikware aus Genf. Er leert sie heimlich aufs Tablett.' },
            { x: 285, y: 180, r: 28, label: 'Blechkasse', say: 'Ein Blechkasten. Mit einem Preisschild von Frau Özcans Blumenstand. Die Kasse!' },
          ],
          done: { who: 'nino', text: 'Nicht Herr Vogel. Der junge Mann. Er hat heimlich Fabrikware hineingelegt. Und die Kasse gestohlen.' },
        },
        D('erz', 'Nino will aufstehen. Und vergisst, wie eng die Gasse ist. KLONK. Kopf gegen den Gemüseständer.', { scene: { name: 'markt', opts: { actors: [NINO_L] } }, sfx: 'bonk', cue: { type: 'brille', at: 'end', from: { x: 85, y: 160 }, to: { x: 300, y: 255 }, landing: 'splash', arc: 100 } }),
        D('erz', 'Direkt in den Wassereimer bei Frau Özcans Blumenstand. Eine Ente schaut zu. Quakt einmal. Die zweite quakt auch. Die dritte hat Besseres zu tun.', { sfx: 'quack3' }),
        D('leyla', 'Ich hol sie.', { scene: { name: 'markt', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        {
          type: 'choose',
          question: { who: 'nino', text: 'Wer hat die Kasse genommen? Tipp darauf.' },
          options: [
            { ...suspect('vogel', SV.tablett(0, 0, 1), 'Herr Vogel'), img: 'tablett', correct: false, say: 'Herr Vogel stand die ganze Zeit vorne bei den Kunden. Er hat gelacht und Kostproben verteilt.' },
            { ...suspect('luca', SV.schachtel(0, 0, 1), 'Luca'), img: 'schachtel', correct: true, say: 'Luca! Er hat hinten die Schachteln geleert. Und die Kasse versteckt.' },
            { ...suspect('brunner', SV.wind(0, 0, 1), 'Der Wind'), img: 'wind', correct: false, say: 'Der Wind? Kann der Wind eine Kasse tragen? Nein.' },
          ],
          hint: { who: 'leyla', text: 'Wer war hinter dem Stand ganz allein?' },
        },
        D('brunner', 'Luca. Was haben Sie da hinten stehen?', { scene: { name: 'markt', opts: { actors: [{ who: 'brunner', x: 90, y: 292, h: 175 }, { who: 'luca', x: 300, y: 292, h: 170 }] } } }),
        D('erz', 'Luca schaut auf den Boden. Onkel Brunner holt die Kasse hervor. Und eine leere Kartonschachtel. Herr Vogel wird sehr still.', { sfx: 'klack' }),
        D('brunner', 'Echte Urner Spezialitäten. Ich schaue das nach. Gut gemacht, Nino.'),
        D('gerber', 'Dein Grossvater hatte dasselbe Werkzeug. Hat es auch in einer Gasse benutzt. Ich glaube, er hatte danach eine Beule am Kopf.', { scene: { name: 'markt', opts: { actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('gerber', 'Augen täuschen manchmal. Ohren seltener.'),
        D('mila', 'ICH hab den Fall gelöst. Ich hab dem Mann mit dem Schnauz in die Augen geschaut und sofort GEWUSST.', { scene: { name: 'markt', opts: { actors: [{ who: 'mila', x: 200, y: 292, h: 140, enter: 'pop' }, NINO_L, { who: 'leyla', x: 320, y: 292, h: 160 }] } }, sfx: 'pop' }),
        D('leyla', 'Du hast ihm eine Kostprobe aus der Hand gezwickt.'),
        D('mila', 'Das war mein PLAN!'),
        D('leyla', 'Total klar.'),
        { type: 'reward', note: 'Genügend', zettel: { text: 'Nicht alles, was gut riecht, ist auch gut. Manchmal muss man hinhören, nicht hinschauen.', icon: 'lauschtrichter' } },
      ],
    },

    // ===================== FALL 3 — Der stumme Zeuge (Buch 03, V6) =====================
    {
      id: 2, title: 'Der stumme Zeuge', place: 'Bäckerei', scene: 'hinterhof', tool: 'lauschtrichter',
      steps: [
        D('erz', 'Hinhören. Nicht hinschauen. Nino schliesst die Augen. Und schüttelt die Ledermappe. Ganz leicht.', { scene: { name: 'gartenhaus', opts: { actors: [NINO] } }, sfx: 'klirr' }),
        {
          type: 'find', scene: { name: 'gartenhaus', opts: {} }, lupe: false,
          intro: { who: 'nino', text: 'Klirr. Etwas Metallisches. Irgendwo innen. Tipp auf die Mappe und such den versteckten Knopf.' },
          hint: 'Tipp auf die Ledermappe auf dem Tisch.',
          hotspots: [{ x: 80, y: 150, r: 32, label: 'Versteckter Knopf', say: 'Ein Knopf, versteckt unter einer Naht. Ein schmaler Schlitz geht auf.', svg: `<circle cx="80" cy="150" r="3" fill="#B8860B" opacity=".8"/>` }],
          done: { who: 'nino', text: 'Ein kleines Hörrohr aus Messing. E. N. Der Lauschtrichter. Wer die Wahrheit hören will, muss leise sein.' },
        },
        D('erz', 'Nino hält das Hörrohr ans Ohr. Die Welt wird LAUT. Der Brunnen klingt wie ein Wasserfall. Ein Spatz trommelt wie ein Specht.', { sfx: 'noiseburst' }),
        D('nino', 'WRRRRR! Herrn Mettlers Auto! Neues Werkzeug: Lauschtrichter. Hört alles. ALLES. Vorsicht bei Autos.', { sfx: 'car' }),
        D('buehler', 'Weisch was, Nino … Nein. Ich weiss gar nichts. Meine Katze. Weg. Seit gestern. Einfach weg.', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'buehler', x: 310, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'Herr Bühler schweigt. In Bärlingen ist das ein Alarmsignal. Agent 0815 übernimmt.', { anim: 'brille' }),
        D('mila', 'ICH AUCH!', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'buehler', x: 310, y: 292, h: 175 }, NINO_L, { who: 'mila', x: 190, y: 292, h: 130, enter: 'pop' }] } }, sfx: 'pop' }),
        D('brunner', 'Also, eine Katze, die wegläuft. Das ist wahrscheinlich der Föhn. Tiere spüren den Föhn.', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'brunner', x: 320, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'In Bärlingen hat es keinen Föhn.'),
        D('brunner', 'Oder der Wind. Ein SEHR starker, äusserst UNGEWÖHNLICHER Wind.'),
        D('kummer', 'Hm.', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'kummer', x: 320, y: 292, h: 175 }, NINO_L] } } }),
        {
          type: 'hold', scene: { name: 'hinterhof', opts: {} }, ms: 3000,
          intro: { who: 'leyla', text: 'Mit dem Lauschtrichter hörst du alles. Zu viel. Vielleicht musst du nicht alles hören. Sondern das Richtige. Leg den Finger auf den Trichter. Und halt ganz still.' },
          noises: [{ x: 60, y: 70, icon: '⏰', sfx: 'tick' }, { x: 130, y: 110, icon: '🧊', sfx: 'fridge' }, { x: 300, y: 60, icon: '🚌', sfx: 'horn' }, { x: 340, y: 130, icon: '🤧', sfx: 'sneeze' }, { x: 210, y: 90, icon: '🦆', sfx: 'quack' }, { x: 250, y: 150, icon: '🪰', sfx: 'fly' }],
          done: { who: 'nino', text: 'Die Welt wird ruhig. Und da, fast zu leise: ein Miauen. Schwach. Verängstigt. Hinter dem Gebäude.' },
        },
        {
          type: 'listenfind', scene: { name: 'hinterhof', opts: {} }, target: { x: 330, y: 232, r: 38 }, sfx: 'miau', range: 220,
          intro: { who: 'nino', text: 'Zieh den Trichter über den Hinterhof. Wo ist das Miauen am lautesten? Dort tipp hin.' },
          foundSprite: { name: 'katze', h: 48, fallback: O.katze(330, 232, 1.2) },
          cue: { type: 'brille', from: { x: 85, y: 165 }, to: { x: 330, y: 240 }, landing: 'klack', arc: 90 },
          done: { who: 'leyla', text: 'KRACKS. Die Katze auf dem Kopf. Die Brille im Loch. Du hast die Katze gefunden. Oder sie dich.' },
        },
        D('nino', 'Das Loch ist kein normales Loch. Die Ränder sind glatt. Jemand hat hier gegraben. Mit einem Spaten. Nachts.', { scene: { name: 'hinterhof', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        D('leyla', 'Der stumme Zeuge. Sie kann nicht reden. Aber sie hat alles mitbekommen.'),
        D('buehler', 'Büsi. BÜSI. Wo WARST du? Ich hab dich gesucht, ich hab sogar mit dem Postboten geredet!', { scene: { name: 'hinterhof', opts: { actors: [{ who: 'buehler', x: 300, y: 292, h: 175 }, NINO_L], extra: Art.sprite('katze_mauer', 200, 185, 44, O.katze(200, 185, 1)) } } }),
        D('gerber', 'Im Hinterhof der Bäckerei lag früher ein Garten. Dein Grossvater hat dort manchmal … Egal. Stell die richtigen Fragen.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('erz', 'Abends. Der Lauschtrichter am Ohr. Neun Schläge, also drei nach neun. Und dann, aus Richtung Bäckerei: Schritte. Kratzen. Metall auf Erde.', { scene: { name: 'hinterhof', opts: { fx: 'night' } }, sfx: 'dig' }),
        D('leyla', 'Mein Fenster geht auf den Hinterhof. Ich hab die Schritte gehört. Ohne Lauschtrichter.', { scene: { name: 'hinterhof', opts: { fx: 'night', actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        D('erz', 'Eine Gestalt kniet am Loch. Ein kleiner Spaten in der Hand. Nino richtet den Lauschtrichter auf die Gestalt. Sein Herz schlägt laut.', { sfx: 'dig' }),
        D('imhof', 'Bitte sei noch da. Bitte sei noch da.', { scene: { name: 'hinterhof', opts: { fx: 'night', actors: [{ who: 'imhof', x: 300, y: 292, h: 170 }] } } }),
        {
          type: 'choose', layout: 'icons',
          question: { who: 'nino', text: 'Was hörst du in der Stimme? Ist der Mann böse? Oder hat er Angst? Tipp darauf.' },
          options: [
            { label: 'Böse', img: 'gesicht_boese', svg: SV.boese(0, 0, 1), correct: false, say: 'Nein. Kein Dieb redet so. Hör nochmal hin.' },
            { label: 'Angst', img: 'gesicht_angst', svg: SV.angst(0, 0, 1), correct: true, say: 'Angst. Der Mann ist kein Dieb. Der Mann hat Angst.' },
          ],
          hint: { who: 'leyla', text: 'Hör auf die Stimme. Leise. Traurig.' },
        },
        D('imhof', 'Mein Name ist Imhof. Meine Grossmutter hat hier vor fünfzig Jahren eine Kiste vergraben. Schmuck. Hier war ihr Garten, bevor die Bäckerei kam. Ich hätte einfach fragen sollen.', { scene: { name: 'hinterhof', opts: { fx: 'night', actors: [{ who: 'imhof', x: 300, y: 292, h: 170 }, NINO_L] } } }),
        D('nino', 'Warum haben Sie nicht?'),
        D('imhof', 'Weil ich dachte, es ist dumm. Eine alte Kiste suchen, nach so langer Zeit.'),
        D('nino', 'Ist es nicht.'),
        {
          type: 'reveal', mode: 'dig', need: 60, brush: 26, sfx: 'dig',
          intro: { who: 'mila', text: 'TIEFER! Schätze sind IMMER tief! Grab mit dem Finger die Erde weg.' },
          hint: 'Reib mit dem Finger über die Erde. Überall.',
          over: SV.erde(260), under: SV.kiste(130, 150, 1.6),
          cursor: `<g><path d="M-6 -20 L6 -20 L4 4 L-4 4 Z" fill="#8B6B44"/><path d="M-10 4 L10 4 L7 22 L-7 22 Z" fill="#9AA0A8" stroke="#555"/></g>`,
          done: { who: 'imhof', text: 'Ein Ring. Eine Brosche. Eine alte Taschenuhr. Sie hat immer gesagt: Irgendwann holst du sie. Ich hab vierzig Jahre gebraucht. Sie tickt noch.' },
        },
        D('erz', 'Tick. Tick. Tick. Wie ein kleines Herz, das nie aufgehört hat zu schlagen. Herr Bühler schnäuzt sich. Und weint. Die Katze putzt sich die Pfote.', { scene: { name: 'hinterhof', opts: { actors: [{ who: 'buehler', x: 300, y: 292, h: 175 }, { who: 'imhof', x: 100, y: 292, h: 165 }], extra: Art.sprite('katze_mauer', 200, 185, 44, O.katze(200, 185, 1)) } }, sfx: 'tick' }),
        D('mila', 'ICH hab die Katze gefunden. Ich hab gesagt, sie ist hinter der Bäckerei.', { scene: { name: 'hinterhof', opts: { actors: [{ who: 'mila', x: 200, y: 292, h: 140, enter: 'pop' }, NINO_L, { who: 'leyla', x: 320, y: 292, h: 160 }] } }, sfx: 'pop' }),
        D('nino', 'Du hast gesagt, sie ist auf dem Mond.'),
        D('mila', 'Das war mein ERSTER Tipp. HINTER DER BÄCKEREI WAR MEIN DRITTER!'),
        D('leyla', 'Einwandfrei.'),
        { type: 'reward', note: 'Genügend', zettel: { text: 'Ohren sind die besseren Augen. Wer den Schlüssel hat, hat noch lange nicht die Tür gefunden.', icon: 'generalschluessel' } },
      ],
    },

    // ===================== FALL 4 — Die verschlossene Werkstatt (Buch 04, V6) =====================
    {
      id: 3, title: 'Die verschlossene Werkstatt', place: 'Werkstatt', scene: 'werkstatt', tool: 'generalschluessel',
      steps: [
        D('erz', 'Draussen regnet es leise. Die Tropfen klopfen aufs Dach wie kleine Finger, die etwas suchen. Nino sucht den Schlüssel. Jede Tasche, jede Naht. Nichts.', { scene: { name: 'gartenhaus', opts: { fx: 'rain', actors: [NINO] } } }),
        {
          type: 'reveal', mode: 'rub', need: 55, brush: 24,
          intro: { who: 'nino', text: 'Wer den Schlüssel hat, hat noch lange nicht die Tür gefunden. Streich mit dem Daumen über die Mappe. Über jede Naht.' },
          hint: 'Streich mit dem Finger über das Leder. Überall.',
          over: SV.leder(260), under: SV.messingstreifen(130, 130, 1.4),
          done: { who: 'nino', text: 'An der Seite gibt das Leder nach. Ein flacher Messingstreifen. Drei Löcher, zwei Schlitze. Wie ein Schlüssel, der seine Zähne verloren hat.' },
        },
        D('opa', 'Nicht jeder Schlüssel passt in ein Schloss. Manche passen auf eine Idee.', { sfx: 'whoosh' }),
        D('erz', 'Auf dem Schulweg probiert Nino den Schlüssel. Zuerst am Schloss des Brunnens.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [NINO_L] } }, cue: { type: 'brille', at: 'end', sprite: 'generalschluessel', fallback: `<rect x="-14" y="-3" width="28" height="6" fill="#C9A227" stroke="#8A6A10"/>`, from: { x: 85, y: 180 }, to: { x: 205, y: 222 }, landing: 'splash', quack: true, arc: 40, dur: 500 } }),
        D('erz', 'Dann am Veloständer. Die Kette wickelt sich um den Ärmel. Fester. Und FESTER. Leyla geht vorbei. Schaut kurz. Sagt nichts. Muss sie auch nicht.', { scene: { name: 'schule', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165, enter: 'right' }] } }, sfx: 'klirr' }),
        D('buehler', 'HEY! Nussgipfeli sind HEILIG! Und weisch was: Die Werkstatt vom alten Neuhaus ist zu. Von INNEN. Und niemand ist drin. Verrückt, gäll?', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'buehler', x: 310, y: 292, h: 175 }, NINO_L] } }, sfx: 'klack' }),
        D('nino', 'Die Werkstatt? Opa Ernsts Werkstatt?'),
        D('kummer', 'Hm.', { scene: { name: 'kirchplatz', opts: { actors: [{ who: 'kummer', x: 320, y: 292, h: 175 }, NINO_L] } }, sfx: 'klirr' }),
        D('nino', 'Von innen verriegelt? Und niemand drin? Herr Kummer hat einhundertsiebenundzwanzig Schlüssel. Er ist bei Nummer vierunddreissig.'),
        D('brunner', 'Wahrscheinlich hat ein Luftzug den Riegel — Es gibt Luftzüge, die gehen um die Ecke. Physikalisch MÖGLICH.', { scene: { name: 'kirchplatz', opts: { actors: [{ who: 'brunner', x: 320, y: 292, h: 175 }, NINO_L] } } }),
        D('mila', 'ICH AUCH! Museumswächterinnen bewachen das Museum. Das ist mein JOB.', { scene: { name: 'kirchplatz', opts: { actors: [{ who: 'mila', x: 200, y: 292, h: 140, enter: 'pop' }, NINO_L, { who: 'kummer', x: 330, y: 292, h: 170 }] } }, sfx: 'whistle', cue: { type: 'pigeons', at: 'start', x: 250, y: 70 } }),
        D('nino', 'Du bist fünf.'),
        D('mila', 'Fünf und DREI VIERTEL. Und ich hab eine Pfeife.', { sfx: 'whistle' }),
        D('erz', 'Herr Kummer öffnet das Schloss mit Schlüssel siebenundvierzig. Den Riegel schiebt er mit dem Taschenmesser zurück. Langsam. Sein Gesicht bleibt so ausdruckslos wie immer.', { sfx: 'klirr' }),
        D('nino', 'Die Werkstatt riecht nach Holz und Öl. Und nach Opa. Messing und Pfefferminz. Und an der Wand: ein Bauplan. Mit Opas Handschrift in den Ecken.', { scene: { name: 'werkstatt', opts: { actors: [NINO_L] } } }),
        {
          type: 'align', start: { x: 70, y: 235 }, target: { x: 150, y: 140 }, snap: 16, cross: { x: 150, y: 140 },
          intro: { who: 'nino', text: 'Halt den Messingstreifen über den Plan. Schieb ihn, bis die Löcher genau auf den Linien liegen.' },
          plan: SV.bauplan(), template: SV.messingstreifen(0, 0, 1),
          done: { who: 'nino', text: 'Durch ein Loch, genau in der Mitte: ein winziges Kreuz. Mit Bleistift. Da muss ich hin.' },
        },
        {
          type: 'find', scene: { name: 'werkstatt', opts: {} }, lupe: false,
          intro: { who: 'nino', text: 'Das Kreuz zeigt eine Stelle im Raum. Tipp auf das Brett, das lockerer sitzt als die anderen.' },
          hint: 'Tipp auf das Brett am Boden, das anders aussieht.',
          hotspots: [{ x: 200, y: 268, r: 36, label: 'Lockeres Brett', say: 'Das Brett gibt nach. Kein Nagel hält es fest. Darunter: ein Hohlraum. Dunkel.', svg: `<path d="M150 262 L250 258" stroke="#2a1a0a" stroke-width="3" opacity=".5"/>` }],
          cue: { type: 'brille', from: { x: 85, y: 160 }, to: { x: 200, y: 268 }, landing: 'klack', arc: 70 },
          done: { who: 'leyla', text: 'Nicht schon wieder. Leer. Nur ein Abdruck im Staub. Ein kleines Oval. So gross wie eine Taschenuhr.' },
        },
        D('nino', 'Jemand war vor mir hier. Und hat etwas mitgenommen. Herr Kummer hat den Schlüssel. Er war heute Morgen als Erster hier.', { scene: { name: 'werkstatt', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        D('leyla', 'Wenn Herr Kummer in die Werkstatt will, braucht er kein Fenster. Er hat siebenundvierzig Schlüssel.'),
        {
          type: 'find', scene: { name: 'werkstatt', opts: {} }, lupe: true,
          intro: { who: 'nino', text: 'Das Fenster. Schau mit der Lupe ganz genau am Rahmen. Findest du etwas, das nicht dorthin gehört?' },
          hint: 'Fahr mit der Lupe über das Fenster. Links.',
          hotspots: [{ x: 62, y: 128, r: 28, label: 'Grüner Draht', say: 'Ein dünner Draht. Grün. Um den Riegel gewickelt. Damit kann man den Riegel von AUSSEN zuziehen.', svg: `<path d="M50 118 Q62 128 58 140 Q66 134 74 138" stroke="#2E8B3A" stroke-width="2" fill="none"/>` }],
          done: { who: 'leyla', text: 'Blumendraht. Grün. Null Komma acht Millimeter. Aus dem Laden meiner Mutter.' },
        },
        D('leyla', 'Vier Kundinnen haben diese Woche grünen Blumendraht gekauft. Drei wohnen in Bärlingen. Eine kam von auswärts: Frau Zürcher, aus Alpnach.', { scene: { name: 'museum', opts: { actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        {
          type: 'find', scene: { name: 'museum', opts: { actors: [{ who: 'frau1', x: 180, y: 292, h: 150 }, { who: 'zuercher', x: 240, y: 292, h: 150 }, { who: 'frau2', x: 300, y: 292, h: 150 }] } }, lupe: false,
          intro: { who: 'nino', text: 'Drei Frauen sitzen auf der Bank vor dem Museum. Eine hält eine alte silberne Taschenuhr in der Hand. Tipp auf sie.' },
          hint: 'Schau auf die Hände. Wer hält eine Uhr?',
          hotspots: [{ x: 240, y: 225, r: 34, label: 'Frau Zürcher', say: 'Eine kleine Frau mit grauen Haaren. Der Mantel ist zu gross. In der Hand: die Taschenuhr. Alt. Silbern.', svg: Art.sprite('taschenuhr', 250, 245, 24, `<circle cx="250" cy="245" r="10" fill="#E6E9EE" stroke="#8C93A0" stroke-width="2"/>`) }],
          misses: [{ x: 180, y: 225, r: 30, say: 'Sie hat keine Uhr. Schau genauer.' }, { x: 300, y: 225, r: 30, say: 'Sie auch nicht. Wer hält die Uhr?' }],
          done: { who: 'zuercher', text: 'Mein Mann hat sie Ihrem Grossvater gegeben. Zur Reparatur. Dann ist Ihr Grossvater … Ich hab sie beim Aufräumen gefunden. Und einfach eingesteckt.' },
        },
        D('zuercher', 'Aber sie hat mich nicht in Ruhe gelassen. Ihr Grossvater hat sie REPARIERT. Ich wollte sie zurückbringen. Und dann hab ich sie doch wieder mitgenommen. Weil ich sie nicht loslassen konnte.', { scene: { name: 'museum', opts: { actors: [{ who: 'zuercher', x: 300, y: 292, h: 170 }, NINO_L] } }, sfx: 'tick' }),
        D('nino', 'Behalten Sie sie. Opa hat sie für Ihren Mann repariert. Sie gehört Ihnen.'),
        D('mila', 'ICH hab den Fall gelöst. Ich hab die Werkstatt BEWACHT. Museumswächterinnen sind WICHTIG.', { scene: { name: 'museum', opts: { actors: [{ who: 'mila', x: 200, y: 292, h: 140, enter: 'pop' }, NINO_L, { who: 'leyla', x: 320, y: 292, h: 160 }] } }, sfx: 'whistle' }),
        D('leyla', 'Stimmt eigentlich.'),
        D('nino', 'Neben der Werkbank, ins Holz geritzt: E. N. Ernst Neuhaus. Opa. Und daneben: R. B. Wer ist R. B.?', { scene: { name: 'werkstatt', opts: { actors: [NINO_L, { who: 'kummer', x: 320, y: 292, h: 175, enter: 'right' }] } } }),
        D('kummer', 'Hat lang genug gedauert, bis du das findest.', { sfx: 'klirr' }),
        { type: 'reward', note: 'Genügend', zettel: { text: 'Nicht jede verschlossene Tür will dich draussen halten. Manche Wahrheiten sieht man nur im Dunkeln.', icon: 'nachtbrille' } },
      ],
    },

    // ===================== FALL 5 — Die unsichtbare Nachricht (Buch 05, V6) =====================
    {
      id: 4, title: 'Die unsichtbare Nachricht', place: 'Gemeinde', scene: 'anschlagbrett', tool: 'nachtbrille',
      steps: [
        D('erz', 'Es ist dunkel im Gartenhaus. Der Strom ist ausgefallen. In ganz Bärlingen. Weil ein Marder in die Trafostation gebissen hat. Mama hat Kerzen angezündet.', { scene: { name: 'gartenhaus', opts: { fx: 'candle', actors: [NINO] } } }),
        {
          type: 'find', scene: { name: 'gartenhaus', opts: { fx: 'candle' } }, lupe: false,
          intro: { who: 'nino', text: 'Manche Wahrheiten sieht man nur im Dunkeln. Am Boden der Mappe ist ein Wulst. Fest. Rund. Drück darauf.' },
          hint: 'Tipp auf die Ledermappe auf dem Tisch.',
          hotspots: [{ x: 80, y: 150, r: 32, label: 'Wulst', say: 'KLICK. Das Futter löst sich. Eine kleine Lederkappe mit Messingring und einem winzigen Schalter.' }],
          done: { who: 'nino', text: 'Violettes Licht. Und auf der Mappe leuchten Buchstaben, die vorher nie da waren: Manche Tinte wartet. Die Nachtbrille.' },
        },
        D('mila', 'WAS IST DAS FÜR EIN LILA LICHT? Agenten haben LILA LICHT! Ich will auch!', { scene: { name: 'gartenhaus', opts: { fx: 'candle', actors: [NINO, { who: 'mila', x: 105, y: 292, h: 140, enter: 'pop' }] } }, sfx: 'pop' }),
        D('nino', 'Raus, Mila. Geheim heisst —'),
        D('mila', 'MAMA! NINO HAT EINE GEHEIMWAFFE!', { sfx: 'bonk', cue: { type: 'shake', who: 'mila', at: 'start' } }),
        D('erz', 'Am nächsten Morgen. QUIETSCH. Das Postauto bremst so scharf, dass man es bis zum Marktplatz hört. Auf der Strasse steht eine Kuh. Braun. Breit. Sie kaut. Langsam.', { scene: { name: 'marktplatz', opts: { bell: true, extra: Art.sprite('postauto', 90, 262, 60, O.postauto(90, 262, 1.2)) + Art.sprite('kuh', 300, 268, 56, SV.kuh(300, 268, 1)) } }, sfx: 'brakes', cue: { type: 'pause', ms: 300 } }),
        D('gerber', 'Bärlingen. Der Ärmste schafft es einfach nie.', { sfx: 'muh' }),
        D('buehler', 'Weisch was, Nino: Am Anschlagbrett hängt jeden Morgen ein leerer Zettel. LEER. Brunner reisst sie ab. Nächster Morgen: wieder einer. Meine Katze hat das Brett angestarrt. Und die Katze hat immer recht.', { scene: { name: 'baeckerei', opts: { actors: [{ who: 'buehler', x: 310, y: 292, h: 175 }, NINO_L] } } }),
        D('brunner', 'Wahrscheinlich ein Streich. Oder der Wind.', { scene: { name: 'anschlagbrett', opts: { actors: [{ who: 'brunner', x: 320, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'Kann der Wind Zettel an ein Brett PINNEN?'),
        D('brunner', 'Ein SEHR starker, ÄUSSERST ungewöhnlicher Wind. Mit einem Reissnagel im … Helikopterrotor.'),
        D('kummer', 'Hm.', { scene: { name: 'anschlagbrett', opts: { actors: [{ who: 'kummer', x: 320, y: 292, h: 175 }, NINO_L] } } }),
        {
          type: 'reveal', mode: 'uv', need: 50, brush: 34, sfx: 'uv',
          intro: { who: 'nino', text: 'Abends. Gartenhaus. Dunkelheit. Ich halte den Zettel unter das violette Licht. Fahr mit dem Licht über das Papier.' },
          hint: 'Fahr mit dem lila Licht über den Zettel. Überall.',
          over: SV.zettelpapier(260), under: SV.uvbild('bruecke'), cursor: SV.uvlicht(),
          done: { who: 'nino', text: 'Die Brücke am Tobel wackelt. Schon seit drei Wochen. Bitte reparieren. Die Zettel waren nie leer! Jemand schreibt in unsichtbarer Tinte.' },
        },
        {
          type: 'reveal', mode: 'uv', need: 50, brush: 34, sfx: 'uv',
          intro: { who: 'nino', text: 'Am nächsten Morgen. Ein neuer Zettel. Ich fange ihn ab, bevor Onkel Brunner ihn abreissen kann. Licht drauf.' },
          hint: 'Fahr mit dem lila Licht über den Zettel. Überall.',
          over: SV.zettelpapier(260), under: SV.uvbild('brunnen'), cursor: SV.uvlicht(),
          done: { who: 'nino', text: 'Der Brunnen im Oberdorf verliert Wasser. Jeden Tag ein bisschen mehr. Sachlich. Wie der erste.' },
        },
        {
          type: 'reveal', mode: 'uv', need: 50, brush: 34, sfx: 'uv',
          intro: { who: 'nino', text: 'Dritter Tag. Dritter Zettel.' },
          hint: 'Fahr mit dem lila Licht über den Zettel. Überall.',
          over: SV.zettelpapier(260), under: SV.uvbild('bank'), cursor: SV.uvlicht(),
          done: { who: 'nino', text: 'Die Bank vor dem Altersheim ist kaputt. Die alten Leute können nicht mehr sitzen. Bitte. Es tut ihnen weh. Der klingt anders. Wie ein Hilferuf.' },
        },
        D('leyla', 'Drei Zettel. Drei Probleme. Dieselbe Handschrift. Eng, ordentlich. Jemand, der gewohnt ist zu schreiben.', { scene: { name: 'gartenhaus', opts: { actors: [NINO, { who: 'leyla', x: 105, y: 292, h: 160 }] } } }),
        {
          type: 'taps', scene: { name: 'karte', opts: {} },
          intro: { who: 'nino', text: 'Stimmt das alles? Wir schauen nach. Tipp auf die Brücke am Tobel, auf den Brunnen im Oberdorf und auf die Bank vor dem Altersheim.' },
          hint: 'Tipp auf einen Ort, der leuchtet.',
          targets: [
            { x: 62, y: 212, r: 26, sfx: 'creak', svg: SV.bruecke_klein(), say: { who: 'nino', text: 'Die Brücke wackelt. Ich spüre es unter den Füssen. Das Holz knarrt.' } },
            { x: 205, y: 95, r: 26, sfx: 'drip', svg: SV.brunnen_klein(), say: { who: 'nino', text: 'Der Brunnen tropft. Ein dünner Rinnsal läuft über den Rand.' } },
            { x: 285, y: 250, r: 26, sfx: 'creak', svg: SV.bank_klein(), say: { who: 'nino', text: 'Die Bank hat ein gebrochenes Bein.' } },
          ],
          done: { who: 'nino', text: 'Alles stimmt. Drei echte Probleme. Aber warum unsichtbar?' },
        },
        D('nino', 'Jemand will die Gemeinde blossstellen. Zuerst sammelt er Beweise. Dann geht er an die Zeitung. Vielleicht ist es sogar eine Drohung.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [NINO_L, { who: 'leyla', x: 320, y: 292, h: 165 }] } } }),
        D('leyla', 'Ziemlich viel Aufwand für einen Wutbrief.'),
        D('gerber', 'Unsichtbare Tinte. Dein Grossvater kannte solche Tricks. Du denkst, jemand will Ärger machen. Falsch.', { scene: { name: 'marktplatz', opts: { bell: true, actors: [{ who: 'gerber', x: 90, y: 292, h: 170 }, { who: 'nino', x: 320, y: 292, h: 150 }] } } }),
        D('gerber', 'Nicht jeder, der leise schreibt, will schreien. Wenn niemand deine Stimme hört, schreibst du, wie du dich fühlst.'),
        D('erz', 'Nachts. Die Kirchturmuhr schlägt elf. Also drei nach elf. Nino und Leyla hocken hinter der Hecke beim Anschlagbrett. Es riecht nach nassem Gras und See.', { scene: { name: 'anschlagbrett', opts: { fx: 'night' } }, sfx: 'bell' }),
        D('nino', 'Ein Schatten. Gross. Dunkel. — Bühlers Katze. Sie schaut mich an, als wüsste sie genau, was ich hier tue. Falscher Alarm.', { scene: { name: 'anschlagbrett', opts: { fx: 'night', extra: Art.sprite('katze', 120, 262, 44, O.katze(120, 262, 1)) } }, sfx: 'miau' }),
        D('erz', 'Dann: echte Schritte. Langsam. Eine Gestalt kommt um die Ecke. Klein. Gebeugt. Weisses Haar im Mondlicht. Ein Zettel, ein Reissnagel, eine kleine Flasche. Kein wütender Mann. Eine alte Frau mit einem Pinsel.', { scene: { name: 'anschlagbrett', opts: { fx: 'night', actors: [{ who: 'andermatt', x: 300, y: 292, h: 165, enter: 'right' }] } } }),
        D('erz', 'Nino tritt aus dem Schatten. Zu schnell. Sein Fuss bleibt an der Hecke hängen. RUMS.', { scene: { name: 'anschlagbrett', opts: { fx: 'night', actors: [{ who: 'andermatt', x: 300, y: 292, h: 165 }, NINO_L] } }, sfx: 'bonk', cue: { type: 'brille', at: 'end', from: { x: 85, y: 160 }, to: { x: 235, y: 168 }, landing: 'klack', keep: true, arc: 60 } }),
        D('nino', 'Die Brille steckt im Korkbrett. Zwischen zwei Reissnägeln. Entschuldigung. Ich bin Agent 0815.'),
        D('andermatt', 'Ihr seid die Ersten, die meine Zettel lesen.'),
        D('andermatt', 'Ich melde die Brücke. Ich melde den Brunnen. Ich melde die Bank. Auf der Gemeindeversammlung nicken alle. Aber niemand tut etwas.'),
        {
          type: 'choose', layout: 'icons',
          question: { who: 'nino', text: 'Und warum unsichtbar? Warum schreibt Frau Andermatt mit unsichtbarer Tinte? Tipp darauf.' },
          options: [
            { label: 'Wütend', img: 'gesicht_wuetend', svg: SV.wuetend(0, 0, 1), correct: false, say: 'Nein. Sie ist nicht wütend. Hör nochmal, wie sie redet.' },
            { label: 'Unsichtbar', img: 'gesicht_unsichtbar', svg: SV.unsichtbar(0, 0, 1), correct: true, say: 'Weil sie so schreibt, wie sie sich fühlt. Unsichtbar. Klein, leise, übersehen.' },
          ],
          hint: { who: 'leyla', text: 'Wie fühlt sich jemand, dem niemand zuhört?' },
        },
        D('andermatt', 'Weil ich so schreibe, wie ich mich fühle. Unsichtbar.', { scene: { name: 'anschlagbrett', opts: { fx: 'night', actors: [{ who: 'andermatt', x: 300, y: 292, h: 165 }, NINO_L, { who: 'leyla', x: 190, y: 292, h: 140 }] } } }),
        D('erz', 'Nino nimmt die Sonnenbrille ab. Langsam. Ohne nachzudenken. Klein, leise, übersehen. Das kennt er.'),
        D('leyla', 'Wir haben Ihre Zettel gelesen. Alle drei. Die Brücke wackelt. Der Brunnen tropft. Die Bank ist kaputt. Alles stimmt.'),
        D('andermatt', 'Dein Grossvater hätte auch zugehört.'),
        D('mama', 'Wer hat das geschrieben?', { scene: { name: 'gemeinde', opts: { actors: [{ who: 'mama', x: 310, y: 292, h: 175 }, NINO_L] } } }),
        D('nino', 'Jemand, der lange nicht gehört wurde.'),
        D('mama', 'Erzähl mir alles.'),
        {
          type: 'reveal', mode: 'paint', need: 55, brush: 26, sfx: 'rub',
          intro: { who: 'mila', text: 'Die Brücke wird am Donnerstag repariert. Der Brunnen am Freitag. Die Bank am Samstag. Streich die Bank blau! Mit dem Finger.' },
          hint: 'Reib mit dem Finger über die Bank. Überall.',
          over: SV.bank_grau(260), under: SV.bank_blau(260), cursor: SV.pinsel(),
          done: { who: 'mila', text: 'ICH hab die Bank repariert. Und das Blaue im Gesicht ist TARNUNG. Blaue Tarnung. Die beste Art.' },
        },
        D('erz', 'Frau Andermatt sitzt auf der frisch gestrichenen Bank. Neben ihr drei alte Frauen. Und sie reden. Frau Andermatt redet mit. Laut genug, dass jeder sie hören kann.', { scene: { name: 'altersheim', opts: { actors: [{ who: 'andermatt', x: 200, y: 292, h: 160 }, { who: 'frau1', x: 90, y: 292, h: 155 }, { who: 'frau2', x: 310, y: 292, h: 155 }] } } }),
        D('erz', 'Herr Kummer geht vorbei. Schaut zur Bank. Schaut zu Nino. Nickt. Einmal. Langsam. Für Herrn Kummer ist das ein Applaus.', { scene: { name: 'altersheim', opts: { actors: [{ who: 'kummer', x: 320, y: 292, h: 175, enter: 'right' }, NINO_L] } } }),
        D('nino', 'Ich habe etwas Unsichtbares sichtbar gemacht. Nicht den Zettel. Sondern einen Menschen.'),
        { type: 'reward', note: 'Genügend', final: true, zettel: { text: 'Manche Stimmen hört man nur, wenn man leise genug ist. Nicht alles, was glänzt, will gesehen werden. Manchmal glänzt es, um abzulenken.', icon: 'sonnenbrille' } },
      ],
    },
  ];
};
